### ISSUE TITLE
Built-in dark reader?

### ISSUE THREAD

**Issue by 3oheicrw** [snaildos/Fifo-Browser#101]
As it's always problematic, what about get it as a built-in feature? Some Chromium based browsers even took Dark Reader code and integrated it into their browser (really integrated, not something as a preinstalled extension but embedded as part of the browser). Given they could do this, could we do the same too? Is there any legal issues?

**Comment by snaildos** [comment]
The thing is we are not a "Chromium Based Browser", we use such a stripped down version of Chromium and using our custom FEL (Fifo Extension Layer) it is really hard to support all extensions. Possible I would accept a PR if it was created, but I won't be spending my time on it.
