### ISSUE TITLE
What is cleared when you choose "Clear all history!"?

### ISSUE THREAD

**Issue by 3oheicrw** [snaildos/Fifo-Browser#108]
It seems only the history is cleaned and only partially cleaned. There are still old opened tabs displayed on the newtab page (and there is no way to clear them too). Other site data seems to be not cleared, too. For example, youtube still keeps my setting to use it Dark appearance. If a successful clear everything like on Firefox/Chrome was done, it should revert back to it default appearance which is Light.

**Comment by 3oheicrw** [comment]
Please add the ability to clear all browsing data like what other browsers (Chrome/Firefox) offered. Thanks.

**Comment by snaildos** [comment]
Yup, again we are already aware of this. Only history database will get deleted, autosuggestion, favicons etc won't get deleted, we are working on a fix again on the latest update.

**Comment by 3oheicrw** [comment]
> ![image](https://user-images.githubusercontent.com/46210117/177187121-95b25e8f-8599-4f33-abdc-f3abc71c2933.png) Planned UI

I think it's better to just copy Chrome/Firefox. Browsing data is broad, it's also including site settings,... not only favicon or suggestions.

**Comment by 3oheicrw** [comment]
> Yeah, The problem with this clear system id the fact it requires datastores to be rewritten. This is going to take some time. slightly_frowning_face

Common problem with Electron based browser. I used to submit a very similar issue on the Min browser repo. I'm glad that you are willingly to solve this.

**Comment by snaildos** [comment]
Patched and fixed with v1.2.1
Any more suggestions / bug reports can go straight over to #116
