### ISSUE TITLE
Bookmark doesn't include site icon (favicon?)

### ISSUE THREAD

**Issue by 3oheicrw** [snaildos/Fifo-Browser#110]
The site icon is not saved. To be even more sure, I exported the bookmarks to html and import in Chrome. Confirmed that no site icon included.

**Comment by 3oheicrw** [comment]
Ah, I found the problem. Try opening the exported html in notepad++. Fifo's exported html is having ICON="undefined", also no base64 encoding of the icon saved like on other browsers. On Chrome/Firefox, apart from setting ICON= to the correct location they also save a base64 encoding of that icon. Try exporting bookmarks to html from Chrome/Firefox and open it with notepad++ and you will see how it looks like.

**Comment by 3oheicrw** [comment]
Not really. It seems to be a problem with multi-tabs. You can't reuse the tab you previously bookmarked. In order for it to correctly set ICON you have to open a new tab and create the bookmark from there. If you continue with your current tab, the bookmark will have no icon. It's really weirded.

**Comment by 3oheicrw** [comment]
Well, open a new tab is the trick. But I found another thing that is even more weirded. You can't close the previous tab. If you closed that tab, even if you opened a new tab, the bookmark still has no icon.

**Comment by snaildos** [comment]
We are aware of this, and it will be fixed on #93 
Related to favicons being corrupted.
