### ISSUE TITLE
Does this browser include coin miners?

### ISSUE THREAD

**Issue by va0dl914** [snaildos/Fifo-Browser#113]
Is this browser safe to use? The developer also has a coin miner coded in JavaScript. Did he conveniently put that piece of JS code into this browser which is also a JS project, too? No one will know. This browser is too laggy in my system. Could it be because it's mining coins?

https://github.com/snaildos/SnailMiner

**Comment by snaildos** [comment]
@va0dl914 Out of my 6 years of experience with open source, I gotta say, this is probably the most stupid issue I have ever seen, in my entire life on GitHub. 
1. Yes. Of course its safe. The code is legit open source, if you dont trust us, then compile the code yourself?
2. Yeah, that miner is for another service SnailDOS provides, our creatable hosting allowing the user to mine cryptocurrency and get coins to spend on the hosting in return. **This is an optional feature that the user has to download manually.**

How is this browser laggy in your system? What are you running this on?
You are providing no detail, no version, absolutely nothing.

Thank you again,
for making me spend 1 minute writing a reply that didn't have to be written if you would of just researched.
Continue discussion and conspiracy theory's will result in a blockage of our services.
Stop. Wasting. Our. Time.

**Comment by va0dl914** [comment]
Not so stupid. Who knows WTH you put inside it. Everytime doing a search in address bar, the whole address bar area becomes blank then the whole window becomes blank before the page could be load. Any reloading of page it blanked the whole browser window before it could be reloaded. This is so much lagging. WTH you are doing with this browser? Even old outdated like Pale Moon has better performance than this one. Based on modern Electron, Chromium 95.0.4638.54 is a rock solid foundation, performance of it could be on par with Chrome. Why it is so laggy? You are doing something fishy behind the scene?

**Comment by snaildos** [comment]
@va0dl914 Who knows what the heck we put inside? Is this a joke? Head to your installation directory. Find the app.asar. Download NodeJS. `npx asar extract app.asar fifo-unpacked` and why don't you try to find "What the heck we put inside". As I already mentioned, if you do not trust us, why not just compile it yourself? No one else is facing any of these problems. Your device is most likely outdated by 10 years but whatever. Still no technical infomation of the version you are using, the device specs. How is this helping us in anyway? 
Continuation of these stupid theories without any technical answers will result of you being blocked from our services. 
You are lucky I have not already blocked you.
