### ISSUE TITLE
Known Issues For v1.2.1 (These will be fixed at v1.2.2)

### ISSUE THREAD

**Issue by snaildos** [snaildos/Fifo-Browser#116]
**Please drop bug reports here**
**These bug reports will be ignored if the user is not running v1.2.1**
- [x] Please add Exit to the menu like Chromium based browser. It's really useful. Currently the last entry on the menu on Fifo is Print.
- [x] Please consider provide an option in Settings to disable media autoplay.
- [x] #124
- [x] #114
- [x] Bookmark icons are apparently broken.
- [x] #122 
- [x] #131
- [x] Disable weather in quickmenu newtab not working. (Only in v1.2.2)

**Comment by va0dl914** [comment]
> **Please drop bug reports here** **These bug reports will be ignored if the user is not running v1.2.2**

Where is v1.2.2 to run? Why could I run something not yet available? This statement is so stupid. Isn't this issue is for reporting v1.2.1 bugs that will be fixed in v1.2.2?

Bookmarks has no icons. This is the first impression of me.

**Comment by snaildos** [comment]
> 
uhm.. it literally is available.. its kinda already released but ok

**Comment by snaildos** [comment]
> > **Please drop bug reports here** **These bug reports will be ignored if the user is not running v1.2.2**
> 
> Where is v1.2.2 to run? Why could I run something not yet available? This statement is so stupid. Isn't this issue is for reporting v1.2.1 bugs that will be fixed in v1.2.2?
> 
> Bookmarks has no icons. This is the first impression of me.
Hello, v1.2.2 is in development, it was a typo and you could of kindly responded with "hey I think you might have done a typo" but that's all ok! The bookmarks having no icons, I'll be looking into that right now. Thank you.

**Comment by 3oheicrw** [comment]
I'm a bit late. It seems Electron based browsers are very bad at handling bookmarks. I just tried Min browser, they also don't have bookmarks favicon and even don't allow to export bookmarks to html (only import from html is supported). So please don't too harsh about this.

**Comment by snaildos** [comment]
@3oheicrw Min looks like a really basic browser. I'll try to integrate features min has that we dont. So I will look at seeing if bookmarks work anyway. I mean, at the moment they work fine for me. I guess its some bookmark issue. Gotta look into it a bit more I guess. Also make sure you updated to v1.2.1 otherwise you are missing out of all the bug fixes.

**Comment by 3oheicrw** [comment]
> @3oheicrw Min looks like a really basic browser.

Don't underestimate Min. It has more features than Fifo. Only the Min developers took the minimalism approach in UI design too far. Most Min features could be invoked from the address bar by typing "!". Min commands all started with "!". Min even have translation built-in even though only in beta (Fifo doesn't, isn't it?). Min also seems to use their own homegrown adblocker or they configured cliqz different from us. Min's adblocker doesn't enfore cosmetic filter (Fifo does). So sometimes you will see a blank area (previously filled with ads) when you browsing websites with Min (Fifo automatically hides these blank areas). Min's adblocker is less powerful than Fifo regarding this but they do allow us to add new filter lists (no auto updates from these manually installed local lists I think), but the default filter lists (EasyList and EasyPrivacy) seems able to be auto updated.

**Comment by snaildos** [comment]
> > @3oheicrw Min looks like a really basic browser.
> 
> Don't underestimate Min. It has more features than Fifo. Only the Min developers took the minimalism approach in UI design too far. Most Min features could be invoked from the address bar by typing "!". Min commands all started with "!". Min even have translation built-in even though only in beta (Fifo doesn't, isn't it?). Min also seems to use their own homegrown adblocker or they configured cliqz different from us. Min's adblocker doesn't enfore cosmetic filter (Fifo does). So sometimes you will see a blank area (previously filled with ads) when you browsing websites with Min (Fifo automatically hides these blank areas). Min's adblocker is less powerful than Fifo regarding this but they do allow us to add new filter lists (no auto updates from these manually installed local lists I think), but the default filter lists (EasyList and EasyPrivacy) seem to be able to auto update.

Again, these features will be addressed in our latest versions.

**Comment by snaildos** [comment]
v1.2.2 == Dependency Update
*Note to self* #1

**Comment by snaildos** [comment]
@3oheicrw Could you talk in #124 on what you mean by "Suggestion bar is broken"?

**Comment by snaildos** [comment]
Update on bookmarks being broken, go to %appdata%\fifo\storage\ and then delete "bookmarks.db". This is an issue with our old versions and they seem to not be affected in latest version on Fifo. We wont be providing a way to upgrade the bookmarks database.

**Comment by 3oheicrw** [comment]
> @3oheicrw Could you talk in #124 on what you mean by "Suggestion bar is broken"?

I have said everything I could say on my old posts. You should dig it a bit as they are not burried deep in this repo. Currently not using Fifo, I can't help now. I'm fighting with Adguard addon on Firefox 91.11 ESR. The addon is currently broken.

**Comment by snaildos** [comment]
> > @3oheicrw Could you talk in #124 on what you mean by "Suggestion bar is broken"?
> 
> I have said everything I could say on my old posts. You should dig it a bit as they are not burried deep in this repo. Currently not using Fifo, I can't help now. I'm fighting with Adguard addon on Firefox 91.11 ESR. The addon is currently broken on this Firefox version and I don't want to upgrade to 102.1.0 ESR.

Hi, thank you for your reply. Will be trying hard to implement those features. What made you stop using Fifo?
Kind Regards,
Snail

**Comment by 3oheicrw** [comment]
> What made you stop using Fifo?

Sometimes you need a full blown browser like Chrome or Firefox that small browser like Min or Fifo can't fulfill. I'm using Fifo mostly to watch youtube and you known, any browsers could watch youtube. Why don't I just use Firefox? I kept both Fifo and Firefox for a while before I decided to uninstall the later and wait for the next Fifo release to try it again. I'm not English speaker but I have to read a lot of English texts. My English skills is very bad too. I have not yet had opportunity to recharge it. A full course on IELTS maybe. I have never had any cerificates. I rely almost solely on Google translate to help me.

**Comment by snaildos** [comment]
> > What made you stop using Fifo?
> 
> Sometimes you need a full blown browser like Chrome or Firefox that small browser like Min or Fifo can't fulfill. I'm using Fifo mostly to watch youtube and you known, any browsers could watch youtube. Why don't I just use Firefox? I kept both Fifo and Firefox for a while before I decided to uninstall the later and wait for the next Fifo release to try it again. I'm not English speaker but I have to read a lot of English texts. My English skills is very bad too. I have not yet had opportunity to recharge it. A full course on IELTS maybe. I have never had any cerificates. I rely almost solely on Google translate to help me.

Ah, ok, Will be looking at adding localization into Fifo I guess.

**Comment by 3oheicrw** [comment]
> Ah, ok, Will be looking at adding localization into Fifo I guess.

No. I have no problems with the browser UI in English. My Firefox is in English too. I said about translation extension not localization of the browser UI. I can't live without Simple Translate extension on Firefox 😄

**Comment by porismuu** [comment]
> > > What made you stop using Fifo?
> > 
> > 
> > Sometimes you need a full blown browser like Chrome or Firefox that small browser like Min or Fifo can't fulfill. I'm using Fifo mostly to watch youtube and you known, any browsers could watch youtube. Why don't I just use Firefox? I kept both Fifo and Firefox for a while before I decided to uninstall the later and wait for the next Fifo release to try it again. I'm not English speaker but I have to read a lot of English texts. My English skills is very bad too. I have not yet had opportunity to recharge it. A full course on IELTS maybe. I have never had any cerificates. I rely almost solely on Google translate to help me.
> 
> Ah, ok, Will be looking at adding localization into Fifo I guess.

dear developer when is the new update?
I'm waiting thanks 👍

**Comment by snaildos** [comment]
> > > > What made you stop using Fifo?
> > > 
> > > 
> > > Sometimes you need a full blown browser like Chrome or Firefox that small browser like Min or Fifo can't fulfill. I'm using Fifo mostly to watch youtube and you known, any browsers could watch youtube. Why don't I just use Firefox? I kept both Fifo and Firefox for a while before I decided to uninstall the later and wait for the next Fifo release to try it again. I'm not English speaker but I have to read a lot of English texts. My English skills is very bad too. I have not yet had opportunity to recharge it. A full course on IELTS maybe. I have never had any cerificates. I rely almost solely on Google translate to help me.
> > 
> > 
> > Ah, ok, Will be looking at adding localization into Fifo I guess.
> 
> dear developer when is the new update? I'm waiting thanks 👍

Hello! Thank you for asking us, I'm expecting it to be released by the end of this week. Leaving a :star: on this repo and telling your friends about this project also helps us grow and get new contributors allowing us to develop and complete updates faster. 
We will be notifying users in this issue on status updates on how we are currently going.
Kind regards,
Snail

**Comment by snaildos** [comment]
Oh, also, to everyone in this issue, join our community discord (or our forum!)
https://invite.gg/snaildos (Discord)
https://community.snaildos.com (Forum)
It's so much easier to communicate large feature requests and when upcoming updates are _actually_ set to release!

**Comment by porismuu** [comment]
> > > > > What made you stop using Fifo?
> > > > 
> > > > 
> > > > Sometimes you need a full blown browser like Chrome or Firefox that small browser like Min or Fifo can't fulfill. I'm using Fifo mostly to watch youtube and you known, any browsers could watch youtube. Why don't I just use Firefox? I kept both Fifo and Firefox for a while before I decided to uninstall the later and wait for the next Fifo release to try it again. I'm not English speaker but I have to read a lot of English texts. My English skills is very bad too. I have not yet had opportunity to recharge it. A full course on IELTS maybe. I have never had any cerificates. I rely almost solely on Google translate to help me.
> > > 
> > > 
> > > Ah, ok, Will be looking at adding localization into Fifo I guess.
> > 
> > 
> > dear developer when is the new update? I'm waiting thanks 👍
> 
> Hello! Thank you for asking us, I'm expecting it to be released by the end of this week. Leaving a ⭐ on this repo and telling your friends about this project also helps us grow and get new contributors allowing us to develop and complete updates faster. We will be notifying users in this issue on status updates on how we are currently going. Kind regards, Snail

thanks I have a problem. I cannot run the system.
https://github.com/snaildos/Fifo-Browser/issues/129

**Comment by snaildos** [comment]
Roadmap updated.
We have these features planned and ready.

**Comment by snaildos** [comment]
Adblocker working in incognito will be fixed later. This update has been delayed for way too long.

**Comment by snaildos** [comment]
Released.
