### ISSUE TITLE
Did you build the Windows release on Windows 7?

### ISSUE THREAD

**Issue by 3oheicrw** [snaildos/Fifo-Browser#117]
Please let me know. Thank you.

**Comment by snaildos** [comment]
No, the build runs on Manjaro.

**Comment by 3oheicrw** [comment]
> No, the build runs on Manjaro.

So you cross compile it from Linux?

**Comment by snaildos** [comment]
> > No, the build runs on Manjaro.
> 
> So you cross compile it from Linux?

Yup, can I close this issue?

**Comment by 3oheicrw** [comment]
> > > No, the build runs on Manjaro.
> > 
> > 
> > So you cross compile it from Linux?
> 
> Yup, can I close this issue?

If it was built on Windows 7 or somehow target Windows 7, this explained a lot of thing. On my Windows 8.1, I found the window to be draw in Windows Classic first before the theme of Fifo took effect. This is the sight of an application was built to target Windows 7 or prior (in the case of Electron it must be Windows 7 because Electron doesn't support prior versions of Windows). The reason is the application is expecting Windows 7 Aero but later Windows has no Aero at all. Such application could have compatibility issues on Windows 8.1 and later. This could be the reason for many random performance/redrawing/blanking of address bar and window area problems.

**Comment by 3oheicrw** [comment]
I tested the Min browser which is also Electron and it has no such problems. If I have Linux I could test Fifo on it to see if the same problems exist or not (I guess not). But somehow I can't get Linux running on my system. If you use Manjaro as your daily driver then I think the problems don't exist on Linux and it's Windows specific.

**Comment by 3oheicrw** [comment]
I tried setting Fifo.exe's compatibility to Windows 7 but the problem is still there. I have no idea. The only different between Fifo and Min is Min is using a newer Electron (user agent show Chrome 102, but I think it's irrelevant) and Min for Windows was built natively on Windows with Visual Studio (not cross compiled from Linux like Fifo).
