### ISSUE TITLE
When using Dark theme enable website's dark mode automatically

### ISSUE THREAD

**Issue by 3oheicrw** [snaildos/Fifo-Browser#118]
It's one of the very useful feature of the Min browser and Firefox 102. Websites like github and youtube have built-in dark mode. If the browser is also using Dark theme then these websites should be set to use their dark mode automatically.

**Comment by snaildos** [comment]
I managed to fix the actual browser input, message boxes, etc, but sadly not the site content. 
I am still looking into it. Thank you!

**Comment by snaildos** [comment]
Fixed. :3

**Comment by 3oheicrw** [comment]
> I managed to fix the actual browser input, message boxes, etc, but sadly not the site content. I am still looking into it. Thank you!

This issue is all about the site content man, not the browser UI.

**Comment by 3oheicrw** [comment]
> Fixed. :3

What is really fixed?

**Comment by DI555** [comment]
@snaildos , could be this feature be optional, please!

smth. like with "chech_for_website_dark_mode" option switch, existing either for every kind Fifo skin!

**Comment by snaildos** [comment]
> @snaildos , could be this feature be optional, please!
> 
> smth. like with "chech_for_website_dark_mode" option switch, existing either for every kind Fifo's theme/skin!

#150
