### ISSUE TITLE
net::ERR_CERT_DATE_INVALID

### ISSUE THREAD

**Issue by ateebplayz** [snaildos/Fifo-Browser#131]
**Bug description**
Cant connect to certain websites giving error "Your connection is not private
This website may be trying to steal information from wss://tkr.arc.io/announce, The website certificate has exired, so we blocked connection with to the site.
net::ERR_CERT_DATE_INVALID"

**To Reproduce**
Unknown

**Expected behavior**
Connecting to the website "https://host.snaildos.com/"

**Screenshots**
One
![image](https://user-images.githubusercontent.com/49984737/185092346-b1ee3a1b-7ab8-4077-ae4a-d599fc6e1a4b.png)

**Details:**
 - Operating System: Windows 11
 - Wexond version: Latest?
 - Last known working Wexond version: Unknown

**Comment by snaildos** [comment]
+ a spelling mistake
#116

**Comment by snaildos** [comment]
An option to ignore invalid certificates are added into development branch of v1.2.2 now.
