### ISSUE TITLE
Known Issues For v1.2.2 (These will be fixed at v1.3.0)

### ISSUE THREAD

**Issue by snaildos** [snaildos/Fifo-Browser#147]
**v1.2.3 is a speed bug fix. v1.3.0 is on its way!**
- [x] OOBE spelling / Grammar
- [x] Bookmark menu not showing icons
- [x] OOBE (Disable Third Party)
- [x] Package Updates
- [x] Get rid of the OOBE saying it will erase data when it _wont._
- [x] Dark Mode is not applied
- [x] Bookmarks require CTRL click for mass select but history does not.
- [x] Add Bookmark UI super wonky
- [x] Time is not updated
- [x] Custom images on newtab do not work
- [x] _Possibly look into custom images (Slideshow)_
- [x] See what I can do with the CRX extensions
- [x] #163 

**Possible fixes (May not be done in this update)**

- [x] #150 
- [ ] #207
- [ ] URL preview
- [x] #173
- [ ] #162

**Comment by va0dl914** [comment]
I give you a star. In case you think I'm a troll. BTW, I use Min. When you fixed adblocker not working in incognito window and add the ability to include new filter lists to adblocker, I will revisit this browser.

**Comment by 3oheicrw** [comment]
Is Dark Mode is not applied still an issue? I'm using v1.2.2 and I have github and youtube to turn dark mode automatically.

**Comment by 3oheicrw** [comment]
What is Time is not updated? My Fifo has correct time on newtab.

**Comment by snaildos** [comment]
> What is Time is not updated? My Fifo has correct time on newtab.

Give it a minute and it wont update.

**Comment by snaildos** [comment]
> I give you a star. In case you think I'm a troll. BTW, I use Min. When you fixed adblocker not working in incognito window and add the ability to include new filter lists to adblocker, I will revisit this browser.

ok

**Comment by snaildos** [comment]
> Is Dark Mode is not applied still an issue? I'm using v1.2.2 and I have github and youtube to turn dark mode automatically.

It doesn't migrate for some users. darkContents doesn't get set correctly, it's strange. Will be looking into it.

**Comment by 3oheicrw** [comment]
> I give you a star. In case you think I'm a troll. BTW, I use Min. When you fixed adblocker not working in incognito window and add the ability to include new filter lists to adblocker, I will revisit this browser.

Uhm, these worked out of the box on Min. This is the only thing Fifo is lose to Min now I think (not counting userscripts) :smile:

**Comment by 3oheicrw** [comment]
> > What is Time is not updated? My Fifo has correct time on newtab.
> 
> Give it a minute and it wont update.

It does update.

**Comment by 3oheicrw** [comment]
> > Is Dark Mode is not applied still an issue? I'm using v1.2.2 and I have github and youtube to turn dark mode automatically.
> 
> It doesn't migrate for some users. darkContents doesn't get set correctly, it's strange. Will be looking into it.

So I'm lucky. It works correctly for me :smile:

**Comment by 3oheicrw** [comment]
BTW, updating the Electron engine is the key. Now I no longer experience any problems with the address bar and tab bar.

**Comment by snaildos** [comment]
> BTW, updating the Electron engine is the key. Now I no longer experience any problems with the address bar and tab bar.

That is great. Good to know.

**Comment by 3oheicrw** [comment]
> > Is Dark Mode is not applied still an issue? I'm using v1.2.2 and I have github and youtube to turn dark mode automatically.
> 
> It doesn't migrate for some users. darkContents doesn't get set correctly, it's strange. Will be looking into it.

Almost forgot. Tell these users to delete the old Fifo profile and start with a new one to see if it helps or not. Because I deleted Fifo before I come back so I really started from scratch.

**Comment by jpgpng** [comment]
Hi. What does OOBE mean?

**Comment by jpgpng** [comment]
Installed. First impression: looks not very different from Chrome, so very familiar. When importing bookmarks from Chrome, any bookmarks in the Other bookmarks folder get ignored. In short, only bookmarks in Bookmarks bar get imported and it imported directly to Bookmarks bar of Fifo.

**Comment by jpgpng** [comment]
Fun: when Chrome imports bookmarks, it puts them in the Imported folders, only bookmarks in Bookmarks bar folder get imported directly into Chrome's Bookmarks bar. Fifo doesn't employ any intermediate Imported folder. So when you import one bookmarks.html file twices, the bookmarks get doubled. Fifo doesn't allow mass selecting of bookmarks (only one at a time) so deleting these duplicated bookmarks is a nightmare. Finally I deleted the Fifo directory on `%appdata%` and started again.

**Comment by snaildos** [comment]
> Hi. What does OOBE mean?
Out Of Box Experience.

**Comment by snaildos** [comment]
> Installed. First impression: looks not very different from Chrome, so very familiar. When importing bookmarks from Chrome, any bookmarks in the Other bookmarks folder get ignored. In short, only bookmarks in Bookmarks bar get imported and it imported directly into Bookmarks bar of Fifo.

Yep okay.

**Comment by snaildos** [comment]
> Fun: when Chrome imports bookmarks, it puts them in the Imported folders, only bookmarks in Bookmarks bar folder get imported directly into Chrome's Bookmarks bar. Fifo doesn't employ any intermediate Imported folder. So when you import one bookmarks.html file twices, the bookmarks get doubled. Fifo doesn't allow mass selecting of bookmarks (only one at a time) so deleting these duplicated bookmarks is a nightmare. Finally I deleted the Fifo directory on `%appdata%` and started again.

Yeah, I mean you should be able to mass select bookmarks? Right?

Either way, leave a star on the project, it helps. :star:

**Comment by snaildos** [comment]
Yup, bookmarks can be mass selected, but you need to hold control unlike the history page... This is UI inconsistency and _should_ be fixed.

**Comment by jpgpng** [comment]
> Either way, leave a star on the project, it helps. star

Done.

**Comment by jpgpng** [comment]
> Yup, bookmarks can be mass selected, but you need to hold control unlike the history page... This is UI inconsistency and _should_ be fixed.

It should be able to use Shift key. Select the beginning bookmark. Hold Shift. Select another bookmark and release Shift. All bookmarks between them will also be selected. It should be able to use Ctrl + A to select all, too. These shortcut keys are somewhat universal.

**Comment by jpgpng** [comment]
Another nice to have addition: When multiple bookmarks are selected, add a button beside Delete and Cancel. It's Open all selected bookmarks. It will be Delete, Cancel, Open all. Both Chrome and Firefox have this feature.

**Comment by shlwapi** [comment]
The browser is better than I think. Btw, website content autoplay should be configurable per site too. I'm using Brave and it's a built-in feature. Apart from the global option, Brave offers "Customized behaviors". There are a list of websites that blocked from autoplaying content and a list of websites that allowed to autoplay content. Describing is hard. Better just download Brave and have a look yourself. The settings is in brave://settings/content/autoplay.

**Comment by snaildos** [comment]
> The browser is better than I think. Btw, website content autoplay should be configurable per site too. I'm using Brave and it's a built-in feature. Apart from the global option, Brave offers "Customized behaviors". There are a list of websites that blocked from autoplaying content and a list of websites that allowed to autoplay content. Describing is hard. Better just download Brave and have a look yourself. The settings is in brave://settings/content/autoplay.

That is advanced. That will be added later.

**Comment by peprnp** [comment]
Please don't pollute my Downloads directory with .crx files pls.

**Comment by snaildos** [comment]
> Please don't pollute my Downloads directory with .crx files pls.

Yep, I'll be looking into extensions getting saved into a temporary folder.

**Comment by snaildos** [comment]
> Another nice to have addition: When multiple bookmarks are selected, add a button beside Delete and Cancel. It's Open all selected bookmarks. It will be Delete, Cancel, Open all. Both Chrome and Firefox have this feature.

Considering It.

**Comment by qqmomr** [comment]
Could you add whole page translation like of Chrome? This is a built-in feature of Chrome, no need to install any extensions.

**Comment by pwd96m4a** [comment]
> Could you add whole page translation like of Chrome? This is a built-in feature of Chrome, no need to install any extensions.

Yeah. This feature is what make me unable to break free from Chromium based browsers. On Firefox with translation extensions, it will always open the translated version in newtab under the domain `*.translate.goog`. This broken the site layout. On Chromium instead it intelligently send only the texts to Google's server then got the translated texts back and replaced the original texts. Everything happens dynamically on the same original site, no newtab involved.

**Comment by pwd96m4a** [comment]
Could you add the ability to disable JavaScript? It's much better if it could be configurable per site.

**Comment by snaildos** [comment]
> Could you add whole page translation like of Chrome? This is a built-in feature of Chrome, no need to install any extensions.
1. That breaks the concept of privacy since it uses Chrome's translation.
2. It isn't easy as you think it is. 
3. It's a nightmare
I _might_ look into it in the future.

**Comment by snaildos** [comment]
> Could you add the ability to disable JavaScript? It's much better if it could be configurable per site.

Sadly due to the nature Fifo works, that is impossible. 
I'll need to talk a bit with the Electron team and work out how I could do it.

**Comment by dwzgocl0** [comment]
Could you add the ability to use custom user agent like Min?

**Comment by 3oheicrw** [comment]
> Could you add the ability to use custom user agent like Min?

Why don't just use Min? :smile:

**Comment by 3oheicrw** [comment]
@snaildos I don't think it's still developed so you will not have any answers :smile: 

https://github.com/samuelmaddock/electron-browser-shell/issues/63

**Comment by snaildos** [comment]
> Could you add the ability to use custom user agent like Min?

Why? The user agent is something that should not be tampered with, since it affects how websites understand the browser.
We update the user agent depending on the chromium version.

**Comment by snaildos** [comment]
> @snaildos I don't think it's still developed so you will not have any answers 😄
> 
> [samuelmaddock/electron-browser-shell#63](https://github.com/samuelmaddock/electron-browser-shell/issues/63)

Hence why I'll probably need to fork it.

**Comment by 3oheicrw** [comment]
> > @snaildos I don't think it's still developed so you will not have any answers smile
> > [samuelmaddock/electron-browser-shell#63](https://github.com/samuelmaddock/electron-browser-shell/issues/63)
> 
> Hence why I'll probably need to fork it.

If it's FELv2 like you said then what's FELv1?

**Comment by snaildos** [comment]
> > > @snaildos I don't think it's still developed so you will not have any answers smile
> > > [samuelmaddock/electron-browser-shell#63](https://github.com/samuelmaddock/electron-browser-shell/issues/63)
> > 
> > 
> > Hence why I'll probably need to fork it.
> 
> If it's FELv2 like you said then what's FELv1?

Our old version that did manage to store chrome extensions.

**Comment by jpgpng** [comment]
> > > > @snaildos I don't think it's still developed so you will not have any answers smile
> > > > [samuelmaddock/electron-browser-shell#63](https://github.com/samuelmaddock/electron-browser-shell/issues/63)
> > > 
> > > 
> > > Hence why I'll probably need to fork it.
> > 
> > 
> > If it's FELv2 like you said then what's FELv1?
> 
> Our old version that did manage to store chrome extensions.

So you ditched your own homegrowth and working implementation to use his?

**Comment by snaildos** [comment]
> > > > > @snaildos I don't think it's still developed so you will not have any answers smile
> > > > > [samuelmaddock/electron-browser-shell#63](https://github.com/samuelmaddock/electron-browser-shell/issues/63)
> > > > 
> > > > 
> > > > Hence why I'll probably need to fork it.
> > > 
> > > 
> > > If it's FELv2 like you said then what's FELv1?
> > 
> > 
> > Our old version that did manage to store chrome extensions.
> 
> So you ditched your own homegrowth and working implementation to use his?

It wasn't ours, it was Sentialx's and the project was dead + archived unlike this one. I am not focusing on extensions.

**Comment by jchwdv** [comment]
The browser is currently in good shape. The only bug I think should be fixed before v1.2.3 is https://github.com/snaildos/Fifo-Browser/issues/132

**Comment by snaildos** [comment]
> The browser is currently in good shape. The only bug I think should be fixed before v1.2.3 is #132

Development is slow with current problems and complications happening IRL. Should be returning to the project soon.

**Comment by jpgpng** [comment]
It's advertised that this browser support reading of pdf like Chrome. This is untrue. The pdf file failed to render. What I saw is a blank window.

**Comment by snaildos** [comment]
> It's advertised that this browser support reading of pdf like Chrome. This is untrue. The pdf file failed to render. What I saw is a blank window.

works on my machine

**Comment by jpgpng** [comment]
> > It's advertised that this browser support reading of pdf like Chrome. This is untrue. The pdf file failed to render. What I saw is a blank window.
> 
> works on my machine

Try to see if it works in incognito window.

**Comment by 3oheicrw** [comment]
> > The browser is currently in good shape. The only bug I think should be fixed before v1.2.3 is #132
> 
> Development is slow with current problems and complications happening IRL. Should be returning to the project soon.

What's the problems with you?

**Comment by jpgpng** [comment]
> > > It's advertised that this browser support reading of pdf like Chrome. This is untrue. The pdf file failed to render. What I saw is a blank window.
> > 
> > 
> > works on my machine
> 
> Try to see if it works in incognito window.

Confirmed. Not work on incognito.

https://github.com/snaildos/Fifo-Browser/issues/170

**Comment by snaildos** [comment]
> 

Hmmm, very interesting. Incognito seems to be scuffed. Again, probably something to do with preloads.

**Comment by 3oheicrw** [comment]
> I'm sorry, what?

There are only small and occasionally commits with minor changes. All of the major bugs are still there. This means development speed is very slow. What's going on with you?

**Comment by snaildos** [comment]
> > I'm sorry, what?
> 
> There are only small and occasionally commits with minor changes. All of the major bugs are still there. This means development speed is very slow. What's going on with you?

I am busy, I don't have much time and other SnailDOS projects are taking a large chunk of my time, especially schooling.

**Comment by 3oheicrw** [comment]
> I am busy, I don't have much time and other SnailDOS projects are taking a large chunk of my time, especially schooling.

Real life is more important.

**Comment by 3oheicrw** [comment]
@snaildos I think I no longer needs Dark Reader. Dark Reader becomes kind of a malware now. It can even change the browser's theme! You didn't hear it wrong, the browser's theme, not the website's themes!

https://github.com/darkreader/darkreader/issues/1430

I only discovered this so called "feature" today and I decided to remove it right away and replace with something else!

**Comment by snaildos** [comment]
> 

It doesn't need to be used anyway, dark theme is used automatically with dark theme.
**If** the site supports it, then there will be a dark theme.

**Comment by dbgrgl** [comment]
> It doesn't need to be used anyway, dark theme is used automatically with dark theme. **If** the site supports it, then there will be a dark theme.

The point of Dark Reader is for sites without a built-in dark theme or the built-in dark theme is too ugly! Speaking like you nullified the need of Dark Reader.

**Comment by snaildos** [comment]
> > It doesn't need to be used anyway, dark theme is used automatically with dark theme. **If** the site supports it, then there will be a dark theme.
> 
> The point of Dark Reader is for sites without a built-in dark theme or the built-in dark theme is too ugly! Speaking like you nullified the need of Dark Reader.

Oh, alright. Thanks for the clarification.

**Comment by 3oheicrw** [comment]
On Chrome I still use Dark Reader as it seems it can't change Chrome's theme like on Firefox. On Firefox, I tried various alternatives. Dark Reader has the best performance + features set + ease of use. None of the alternatives (even commercial) could match. This is a fact. But I don't accept it to interfere with the browser's theme. So I will try to find out the best alternative and stick with it on Firefox. As I used to note on this repo Dark Reader can trigger a "Loading. Please wait..." even on supported browser (Firefox) if you override the user agent on about:config. I don't know how much this extension interfered with the browser's internal working. Why an extension like it should check for the browser's user agent? Browser's user agent override is for websites, extensions on Firefox have their own appVersion string to check for which Firefox version they are running on.

**Comment by 3oheicrw** [comment]
Update: on incognito window adblocker currently not work. But this can't stop me from using incognito window. I simple choose to use websites that don't have ads. For watching youtube, I use invidious on incognito window and normal youtube.com on normal window. So far everything is good. But if you could fix incognito window then it's even better.

**Comment by snaildos** [comment]
> Update: on incognito window adblocker currently not work. But this can't stop me from using incognito window. I simply choose to use websites that don't have ads. For watching youtube, I use invidious on incognito window and normal youtube.com on normal window. So far everything is good. But if you could fix incognito window then it's even better.

Sounds great, I am 70% sure I know what the issue is. I am free today, so I gotta finish a couple of websites, EncryptOS (upcoming privacy OS) and fix some bugs on Fifo.

I thank you all for your patience.

**Comment by snaildos** [comment]
Removing "PDF not working in Incognito mode" on our Todolist, but the issue will be kept open.
It is confirmed to be an Electron issue. #170

**Comment by snaildos** [comment]
Fifo Full Dark Theme:
![image](https://user-images.githubusercontent.com/46210117/194749387-c8c9572f-8113-4345-9b34-881a7db66932.png)

**Comment by 44iCdnz** [comment]
> On Chrome I still use Dark Reader as it seems it can't change Chrome's theme like on Firefox. On Firefox, I tried various alternatives. Dark Reader has the best performance + features set + ease of use. None of the alternatives (even commercial) could match. This is a fact. But I don't accept it to interfere with the browser's theme. So I will try to find out the best alternative and stick with it on Firefox. As I used to note on this repo Dark Reader can trigger a "Loading. Please wait..." even on supported browser (Firefox) if you override the user agent on about:config. I don't know how much this extension interfered with the browser's internal working. Why an extension like it should check for the browser's user agent? Browser's user agent override is for websites, extensions on Firefox have their own appVersion string to check for which Firefox version they are running on.

I do not agree. Dark Reader is crucial for me. If not Dark Reader, the browser should have built-in equivalent feature like Samsung Internet Browser on mobile.

**Comment by 44iCdnz** [comment]
> Fifo Full Dark Theme: ![image](https://user-images.githubusercontent.com/46210117/194749387-c8c9572f-8113-4345-9b34-881a7db66932.png)

Is it just the browser's dark theme or the dark mode (Dark Reader like feature that applied to all websites) like of Samsung Internet Browser?

**Comment by snaildos** [comment]
> > Fifo Full Dark Theme: ![image](https://user-images.githubusercontent.com/46210117/194749387-c8c9572f-8113-4345-9b34-881a7db66932.png)
> 
> Is it just the browser's dark theme or the dark mode (Dark Reader like feature that applied to all websites) like of Samsung Internet Browser?

It is a browser theme that is going to be codenamed "Fifo Amoled". Custom Themes will probably be added in a _future update._

**Comment by 44iCdnz** [comment]
> It is a browser theme that is going to be codenamed "Fifo Amoled". Custom Themes will probably be added in a _future update._

What is Custom Themes? What I want is something like Samsung Internet Browser's dark mode for websites, something like Dark Reader. I don't care about browser's ui. The current dark theme is good enough for me.

**Comment by 44iCdnz** [comment]
https://github.com/snaildos/Fifo-Browser/issues/172

**Comment by 44iCdnz** [comment]
https://github.com/snaildos/Fifo-Browser/issues/173

**Comment by 44iCdnz** [comment]
https://github.com/snaildos/Fifo-Browser/issues/174

**Comment by 44iCdnz** [comment]
https://github.com/snaildos/Fifo-Browser/issues/179

**Comment by 44iCdnz** [comment]
You have a new opponent: https://github.com/yessGlory17/programmer-browser

**Comment by snaildos** [comment]
> You have a new opponent: https://github.com/yessGlory17/programmer-browser

Not an opponent and offers no privacy features.

**Comment by snaildos** [comment]
v1.2.3 Release date is set to release on 2023.

**Comment by snaildos** [comment]
Update out this month.

**Comment by snaildos** [comment]
We are skipping v1.3.0 and going straight to v1.3.1 including all v1.3.0 changes and the v1.3.1 changes just to get the 2022 update out of the way.

**Comment by snaildos** [comment]
Update is out on all platforms and will take a day to deploy worldwide. 
Kind regards,
SnailDOS Team
Thank you everyone for your support.
