### ISSUE TITLE
fifo://flags  and fifo://config  pages  ,  feature

### ISSUE THREAD

**Issue by DI555** [snaildos/Fifo-Browser#149]
foa, let me say many thanks for letting Wexond flame to be alive!!!

i would like to ask about features -
fifo://flags  and  fifo://config  pages,

the 1st is exactly of listing flags from the chromium/electron core parameters/options, wich we using in Fifo , to tune it in details !

and the 2nd is the smth of analogue ff's about:config for features, wich have no ui , may be yet, in Fifo..
..for example, the parameters/options forbtabs , liketab_max_width and tab_min_width , could be in fifo://config !!!

**Comment by snaildos** [comment]
> foa, let me say many thanks for letting Wexond flame to be alive!!!
> 
> i would like to ask about features - fifo://flags and fifo://config pages,
> 
> the 1st is exactly of listing flags from the chromium/electron core parameters/options, wich we using in Fifo , to tune it in details !
> 
> and the 2nd is the smth of analogue ff's about:config for features, wich have no ui , may be yet, in Fifo.. ..for example, the parameters/options forbtabs , liketab_max_width and tab_min_width , could be in fifo://config !!!

It's impossible. Electron is a super stripped down version of the Chromium project. Meaning, Flags UI is not even a thing, I would need to build the UI, create everything and it will be a total nightmare. That won't be happening.
Sorry!

**Comment by DI555** [comment]
@snaildos ,
ok, drop the 1st.., leave the 2nd feature..
fifo://config , i ment to bust a bunch of fifo's feagures , that are withoug UI , or temporary wiwhout UI !!!

**Comment by snaildos** [comment]
> @snaildos , ok, drop the 1st.., leave my 2nd feature request.. fifo://config , i ment to bust a bunch of fifo's features , that are withoug UI , or temporary wiwhout UI !!!

settings exist?
