### ISSUE TITLE
https://snaildos.com got redirected to wss://tkr.arc.io/announce

### ISSUE THREAD

**Issue by jpgpng** [snaildos/Fifo-Browser#169]
And not only that, I'm browsing via Fifo and it's telling me that my connection is not private and the site is trying to steal my information!

fifo-error://network-error/net::ERR_CERT_DATE_INVALID

Your connection is not private
This website may be trying to steal information from wss://tkr.arc.io/announce, The website certificate has expired, so we blocked connection with to the site.
Fifo will not allow you to connect to this site. Please open Settings --> Privacy --> Ignore Invalid Certificates.
net::ERR_CERT_DATE_INVALID

I happened so fast but I recall first I could see snaildos.com's content and only a blink later I got redirected to that site.

**Comment by snaildos** [comment]
> And not only that, I'm browsing via Fifo and it's telling me that my connection is not private and the site is trying to steal my information!
> 
> fifo-error://network-error/net::ERR_CERT_DATE_INVALID
> 
> Your connection is not private This website may be trying to steal information from wss://tkr.arc.io/announce, The website certificate has expired, so we blocked connection with to the site. Fifo will not allow you to connect to this site. Please open Settings --> Privacy --> Ignore Invalid Certificates. net::ERR_CERT_DATE_INVALID
> 
> I happened so fast but I recall first I could see snaildos.com's content and only a blink later I got redirected to that site.

Known issue.
It seems to be an issue with either Arc, or the fact Fifo is not ignoring wss:// and I still need to do research upon if it's unsecure to allow invalid certificates on wss or if wss even _has certificates._

**Comment by jpgpng** [comment]
> > And not only that, I'm browsing via Fifo and it's telling me that my connection is not private and the site is trying to steal my information!
> > fifo-error://network-error/net::ERR_CERT_DATE_INVALID
> > Your connection is not private This website may be trying to steal information from wss://tkr.arc.io/announce, The website certificate has expired, so we blocked connection with to the site. Fifo will not allow you to connect to this site. Please open Settings --> Privacy --> Ignore Invalid Certificates. net::ERR_CERT_DATE_INVALID
> > I happened so fast but I recall first I could see snaildos.com's content and only a blink later I got redirected to that site.
> 
> Known issue. It seems to be an issue with either Arc, or the fact Fifo is not ignoring wss:// and I still need to do research upon if it's unsecure to allow invalid certificates on wss or if wss even _has certificates._

Excuse me please, but what is wss? And what is Arc? I don't understand anything.

**Comment by snaildos** [comment]
> > > And not only that, I'm browsing via Fifo and it's telling me that my connection is not private and the site is trying to steal my information!
> > > fifo-error://network-error/net::ERR_CERT_DATE_INVALID
> > > Your connection is not private This website may be trying to steal information from wss://tkr.arc.io/announce, The website certificate has expired, so we blocked connection with to the site. Fifo will not allow you to connect to this site. Please open Settings --> Privacy --> Ignore Invalid Certificates. net::ERR_CERT_DATE_INVALID
> > > I happened so fast but I recall first I could see snaildos.com's content and only a blink later I got redirected to that site.
> > 
> > 
> > Known issue. It seems to be an issue with either Arc, or the fact Fifo is not ignoring wss:// and I still need to do research upon if it's unsecure to allow invalid certificates on wss or if wss even _has certificates._
> 
> Excuse me please, but what is wss? And what is Arc? I don't understand anything.

WSS is Websocket, and Arc is an opt in system that we use on our site that allows profit for us.
https://arc.io (more info here)

**Comment by jpgpng** [comment]
> > > > And not only that, I'm browsing via Fifo and it's telling me that my connection is not private and the site is trying to steal my information!
> > > > fifo-error://network-error/net::ERR_CERT_DATE_INVALID
> > > > Your connection is not private This website may be trying to steal information from wss://tkr.arc.io/announce, The website certificate has expired, so we blocked connection with to the site. Fifo will not allow you to connect to this site. Please open Settings --> Privacy --> Ignore Invalid Certificates. net::ERR_CERT_DATE_INVALID
> > > > I happened so fast but I recall first I could see snaildos.com's content and only a blink later I got redirected to that site.
> > > 
> > > 
> > > Known issue. It seems to be an issue with either Arc, or the fact Fifo is not ignoring wss:// and I still need to do research upon if it's unsecure to allow invalid certificates on wss or if wss even _has certificates._
> > 
> > 
> > Excuse me please, but what is wss? And what is Arc? I don't understand anything.
> 
> WSS is Websocket, and Arc is an opt in system that we use on our site that allows profit for us. https://arc.io (more info here)

What's wrong with that site? Click to your link also trigger a certificate error.

**Comment by snaildos** [comment]
> > > > > And not only that, I'm browsing via Fifo and it's telling me that my connection is not private and the site is trying to steal my information!
> > > > > fifo-error://network-error/net::ERR_CERT_DATE_INVALID
> > > > > Your connection is not private This website may be trying to steal information from wss://tkr.arc.io/announce, The website certificate has expired, so we blocked connection with to the site. Fifo will not allow you to connect to this site. Please open Settings --> Privacy --> Ignore Invalid Certificates. net::ERR_CERT_DATE_INVALID
> > > > > I happened so fast but I recall first I could see snaildos.com's content and only a blink later I got redirected to that site.
> > > > 
> > > > 
> > > > Known issue. It seems to be an issue with either Arc, or the fact Fifo is not ignoring wss:// and I still need to do research upon if it's unsecure to allow invalid certificates on wss or if wss even _has certificates._
> > > 
> > > 
> > > Excuse me please, but what is wss? And what is Arc? I don't understand anything.
> > 
> > 
> > WSS is Websocket, and Arc is an opt in system that we use on our site that allows profit for us. https://arc.io (more info here)
> 
> What's wrong with that site? Click to your link also trigger a certificate error.

It's an arc/browser issue, I already said above in the prior issue I know about it. It'll be fixed later.

**Comment by jpgpng** [comment]
Seems something wrong of Fifo. The link opened fine on Firefox. The connection is secure. Firefox tells it's verified by Amazon.

**Comment by snaildos** [comment]
> Seems something wrong of Fifo. The link opened fine on Firefox. The connection is secure. Firefox tells it's verified by Amazon.

Yeah I know.
