### ISSUE TITLE
Allow to toggle extensions on/off on the fly

### ISSUE THREAD

**Issue by ruanjiasing** [snaildos/Fifo-Browser#171]
Issue ported from skyebrowser. Still applies to Fifo.

https://github.com/skyebrowser/skye/issues/50

**Comment by 44iCdnz** [comment]
@snaildos this is very useful to have, please have a look

**Comment by snaildos** [comment]
Yeah... well...
It isn't a very easy thing to do.
I don't think I'll be looking into this.
