### ISSUE TITLE
fifo://welcome want to: but want to what?

### ISSUE THREAD

**Issue by ghost** [snaildos/Fifo-Browser#172]
This is the first time I set Fifo as default browser. It presented me with this dialog. It doesn't state what it want to do. I have no idea what it's going to do but I choose Allow anyway. What it's really asking me for?

As I'm living outside of the United States the news feature is useless for me as I don't care about these news. I chose to disable it when setup but later I found this doesn't have any effects. I have to turn it off on Settings anyway. Another caveat is Fifo seems to be failed to set itself as the default browser. I choose both the Yes button and the Set default button. Both of them give me an error message about no application to handle ms setting or something like that I'm really sure since it's too fast. I ended up have to go to PC Settings (I'm using Windows 8.1 on my old laptop). Fifo is already set as the default browser and default to open html but not htm. I manually set it to open htm too. Don't know if it's right to do so or not.

p/s: I uninstalled Chrome, Fifo is the only browser.

**Comment by 44iCdnz** [comment]
![Capture](https://user-images.githubusercontent.com/109190757/195146024-7590c46d-4c93-4e56-82ec-2021a1bd857c.PNG)

**Comment by snaildos** [comment]
#147 _should be fixed now._

**Comment by snaildos** [comment]
Please separate the issues; however, Windows 8.1 isn't supported. Regarding news, please ensure you are on latest version. When pressing allow, it opens ms-settings: to change the default apps.

**Comment by snaildos** [comment]
Right, it isn't fixed, I have no clue what the permission place holder is. :/
