### ISSUE TITLE
Bookmark toolbar bug

### ISSUE THREAD

**Issue by ghost** [snaildos/Fifo-Browser#173]
The bookmarks expanded by clicking > don't have their icons and bookmarks folders imported show as (empty) when the fact they are not. The importing of bookmarks from html completed right. I could see these bookmarks on fifo://bookmarks, first I think it failed to import bookmarks folders but it was wrong, it's the bookmark toolbar that is buggy.

**Comment by snaildos** [comment]
Can't reproduce...

**Comment by snaildos** [comment]
Marking as closed since stale.
