### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by ghost** [snaildos/Fifo-Browser#175]
If you open a resource heavy tab, e.g: a youtube video on normal window, if you open incognito window for github (like what I'm doing now as I'm typing from incognito window) the typing of text could become laggy. Most notable is the use of Shift key to have capitalized letter sometimes not work or got delayed. Sometimes some normal key (alphabet key) can also failed to input or got delayed. Most of the time they are just failed to input. The problem disappear after a while (could be some minutes).

**Comment by 44iCdnz** [comment]
My keyboard is OK and my system is not weak. I'm doing that all the time on Chrome (youtube on normal window and github or facebook on incognito window).

**Comment by snaildos** [comment]
You mentioned you used Windows 8/8.1, That could be an issue. For now, I cannot reproduce the issue.
