### ISSUE TITLE
Sometimes tooltip on normal window got carried to incognito window

### ISSUE THREAD

**Issue by ghost** [snaildos/Fifo-Browser#176]
This kind of tooltip: https://www.w3schools.com/css/css_tooltip.asp, e.g: when you hover over a youtube video it will show a description. This tooltip sometimes got carried to incognito window. There is nothing you can do on the incognito window to get rid of it. You have to go back to the normal window and drag your mouse away from the tooltip.

**Comment by snaildos** [comment]
Yep, however, that seems to be an Electron bug.

**Comment by snaildos** [comment]
https://github.com/electron/electron/issues/34422
Could also be a Chromium issue, I had it happen to me a few times on one of my devices. Eventually, this issue will get fixed. For now, it isn't an issue we can fix.
