### ISSUE TITLE
Another Fifo quirk: Fifo can't browse the file system

### ISSUE THREAD

**Issue by 44iCdnz** [snaildos/Fifo-Browser#179]
For example, you copied the path C:\Foo into Chrome, it will be converted to file:///C:/Foo/ and the content of directory Foo will be displayed. Same as when you are browsing a remote file server. Fifo doesn't do this. If you paste C:\Foo into it then it will search for C:\Foo with the default search engine. If you copy Chrome's converted URI file:///C:/Foo/ into Fifo then it will present you with this error:

```
Your file was not found
It may have been moved or deleted. Can't find it at the URL you specified.
ERR_FILE_NOT_FOUND
```

**Comment by snaildos** [comment]
> For example, you copied the path C:\Foo into Chrome, it will be converted to file:///C:/Foo/ and the content of directory Foo will be displayed. Same as when you are browsing a remote file server. Fifo doesn't do this. If you paste C:\Foo into it then it will search for C:\Foo with the default search engine. If you copy Chrome's converted URI file:///C:/Foo/ into Fifo then it will present you with this error:
> 
> ```
> Your file was not found
> It may have been moved or deleted. Can't find it at the URL you specified.
> ERR_FILE_NOT_FOUND
> ```

Yeah since that isn't a relative path, Fifo won't be able to find it, if you do file://C:/pdf.pdf it will work if that pdf exists.
We will not be adding a directory viewer into Fifo.

**Comment by 44iCdnz** [comment]
> > For example, you copied the path C:\Foo into Chrome, it will be converted to file:///C:/Foo/ and the content of directory Foo will be displayed. Same as when you are browsing a remote file server. Fifo doesn't do this. If you paste C:\Foo into it then it will search for C:\Foo with the default search engine. If you copy Chrome's converted URI file:///C:/Foo/ into Fifo then it will present you with this error:
> > ```
> > Your file was not found
> > It may have been moved or deleted. Can't find it at the URL you specified.
> > ERR_FILE_NOT_FOUND
> > ```
> 
> Yeah since that isn't a relative path, Fifo won't be able to find it, if you do file://C:/pdf.pdf it will work if that pdf exists. We will not be adding a directory viewer into Fifo.

file://C:/pdf.pdf is not relative path. Do you understand what relative path mean? All of the paths on this thread are absolute, indeed they are an URI: https://en.wikipedia.org/wiki/Uniform_Resource_Identifier

**Comment by snaildos** [comment]
That is a relative path*.
