### ISSUE TITLE
There is still no shortcut key to zoom in/zoom out

### ISSUE THREAD

**Issue by ruanjiasing** [snaildos/Fifo-Browser#182]
`Ctrl and ++/Ctrl and --` still not yet implemented. We have to go to the menu and zoom with `^` and `v` button.

**Comment by snaildos** [comment]
#147

**Comment by snaildos** [comment]
Implemented, needs testing.

**Comment by snaildos** [comment]
You can do CTRL + Mouse Scroll.
Not sure about keybinds, having some issues with that at the moment, for now, I'll close this. I don't see a use.
If the mouse scroll wheel is a thing, then again, I don't see a use, however, for laptop users, this will probably need to be added.

Any more further discussion? 
Feel free to re-open if you think it is still relevant.

**Comment by ruanjiasing** [comment]
No further discussion, because I can't build Fifo from source so I need to wait until a new release happen to actually test the new feature!

**Comment by ruanjiasing** [comment]
A bit unrelated but I lost the account name **3oheicrw**. All troubles began when I found Github allows you to change your account name. I changed to something else without realizing my previous account name will immediately available to other people. Someone took it and I can't change back to the previous account name. The people with account name **3oheicrw** is not me.
