### ISSUE TITLE
fifo-error://network-error/net::ERR_CERT_DATE_INVALID

### ISSUE THREAD

**Issue by 3oheicrw** [snaildos/Fifo-Browser#184]
Your connection is not private

This website may be trying to steal information from https://imgbb.co/json, The website certificate has expired, so we blocked connection with to the site.
Fifo will not allow you to connect to this site. Please open Settings --> Privacy --> Ignore Invalid Certificates.

net::ERR_CERT_DATE_INVALID

**Comment by snaildos** [comment]
what is the issue here

**Comment by snaildos** [comment]
<img width="341" alt="image" src="https://user-images.githubusercontent.com/46210117/197463803-0a477c88-6a5c-489b-91cc-887641adab54.png">

its literally not secure, and fifo explains how to resolve it.

**Comment by 3oheicrw** [comment]
> <img alt="image" width="341" src="https://user-images.githubusercontent.com/46210117/197463803-0a477c88-6a5c-489b-91cc-887641adab54.png">
> 
> its literally not secure, and fifo explains how to resolve it.

Sorry. It's a typo. The correct address is `imgbb.com`, not `imgbb.co`. I just used the wrong address and Fifo is working as expected here.

**Comment by snaildos** [comment]
Please be more specific when opening an issue next time.

**Comment by snaildos** [comment]
What is the issue? Is this resolved?

**Comment by 3oheicrw** [comment]
> Please be more specific when opening an issue next time.

> What is the issue? Is this resolved?

There is no issue. My English is bad so it seems it confused you. The address I should go is `imgbb.com` but I mistakenly typed `imgbb.co` so I got the certificate error. I checked on Firefox and verified `imgbb.co` is really having certificate problems.
