### ISSUE TITLE
Newtab weather forecast running out of queries

### ISSUE THREAD

**Issue by 3oheicrw-alter-ego** [snaildos/Fifo-Browser#186]
![Capture](https://user-images.githubusercontent.com/116574529/197914272-cc2e50a3-1a22-48cf-9615-ce7556393c7d.PNG)

**Comment by snaildos** [comment]
That isn't an us problem, but just a weather API issue.

**Comment by 3oheicrw-alter-ego** [comment]
> That isn't an us problem, but just a weather API issue.

Not your problem. But you should be informed that there is a problem.

**Comment by snaildos** [comment]
> > That isn't an us problem, but just a weather API issue.
> 
> Not your problem. But you should be informed that there is a problem.

Well, nothing I can do, even if I wanted to.

**Comment by 3oheicrw-alter-ego** [comment]
> > > That isn't an us problem, but just a weather API issue.
> > 
> > 
> > Not your problem. But you should be informed that there is a problem.
> 
> Well, nothing I can do, even if I wanted to.

I know, I only want to let you know that it did happen. Now everything is back to normal.
