### ISSUE TITLE
Expired certificate alerts

### ISSUE THREAD

**Issue by Cohejh** [snaildos/Fifo-Browser#208]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
A setting that alerts you when a website has an expired certificate.

**Describe alternatives you've considered**
Apart from using online tools, there are none. Most major browsers have some kind of equivalent built in.

**Additional context**
Maybe also a ‘Block expired websites’ option as well as a alert feature. An ignore button for expired websites is also useful.

**Comment by snaildos** [comment]
There is a alert, and there is also a ignore button, not sure if this is merged in our big update yet though. Keep track in #147

**Comment by snaildos** [comment]
v1.3.1 is out and should contain everything you asked for.
