### ISSUE TITLE
Unable to export bookmarks to html

### ISSUE THREAD

**Issue by 97tn** [snaildos/Fifo-Browser#220]
Everything is normal and just straight forward like on other browsers until I found it actually didn't write the html file. I tried many times with the same result. The html files are added to recently opened list of Fifo (when you right click on the Fifo icon on task bar when it's running as I recall). If you choose to open the html file from there, Windows will simply tell you the file is not exists.

**Comment by snaildos** [comment]
I'll look into this.

**Comment by snaildos** [comment]
Fifo does not have the functionality of opening HTML files at this current time. However, importing and exporting bookmarks seem to work perfectly. I'll be looking into fixing opening and closing HTML files.
