### ISSUE TITLE
Maintan a version for Windows 7/8.1 users

### ISSUE THREAD

**Issue by hgntn** [snaildos/Fifo-Browser#221]
Please don't jump to the latest greatest Electron version (currently based on Chromium 110). The older stable releases of Electron are still maintained.

https://releases.electronjs.org/

**Comment by snaildos** [comment]
@hgntn Windows 7/8 is dead and I really don't find a need to maintain the Windows 7/8 versions. As I mentioned, there are many alternatives to Windows, if you want privacy.
#218
