### ISSUE TITLE
Hardware Accelerate Problem in windows11/10

### ISSUE THREAD

**Issue by Sentiax** [snaildos/Fifo-Browser#264]
**Bug description**
> **The app window glitches**
> **Devtools doesn't have this problem**

**Screenshots**
![image](https://github.com/snaildos/Fifo-Browser/assets/73078933/ac40d5e3-af3c-4e35-972e-c01b5f525ed8)

**Details:**
 - Operating System: Windows11/Windows10
 - App version: the latest version
 - GTX 1660ti
 - ryzen 7 4800h
 - Tested on rtx 3080 but same problem

**Additional context**
Make a switch that stops hardware accelerate 
I can help I'm an electron dev also
to disable hardware acceleration: 
```ts
//Make a switch and add this line to it
app.disableHardwareAcceleration()
```

**Comment by snaildos** [comment]
Completed in `18779048cd9493faf9a9a1a975b378aad70b6b1b` branch 2023.
