### ISSUE TITLE
Bookmarks problem

### ISSUE THREAD

**Issue by Sentiax** [snaildos/Fifo-Browser#269]
**Bug description**
bookmarks showing a 0 on the list

**Expected behavior**
if bookmarks is 0 don't show bookmarks if you have 1 website in ur bookmarks or more then show bookmarks
**Screenshots**
![image](https://github.com/snaildos/Fifo-Browser/assets/73078933/6c5efe02-5521-4eaf-850d-a5e5bd2657aa)

**Comment by snaildos** [comment]
@Sentiax I do not want to integrate this since I want bookmarks to be togglable rather than automatic.
This won't be added.

**Comment by Sentiax** [comment]
@snaildos, I mean if you already toggled and you have 0 bookmarks then the bookmarks menu won't show but if you have 1 bookmark or more then show the menu ( if u have toggled it)
