### ISSUE TITLE
DNS-over-HTTPS

### ISSUE THREAD

**Issue by iahung2** [snaildos/Fifo-Browser#280]
The Electron platform already supports this feature and the feature has been existed on Chromium for years. Please consider adding support for it. Thank you.

**Comment by snaildos** [comment]
Could you please elaborate? I'm pretty sure Fifo already has this.

**Comment by iahung2** [comment]
> Could you please elaborate? I'm pretty sure Fifo already has this.

No. I don't think Fifo already has this. You could search for DNS over HTTPS Chromium on Google and you could see how the feature is like.

**Comment by snaildos** [comment]
> > Could you please elaborate? I'm pretty sure Fifo already has this.
> 
> No. I don't think Fifo already has this feature. I'm currently not using my PC so I can't give you screenshots. You could search for `DNS over HTTPS Chromium` on Google and you could see how the feature is like. If you are on mobile like me, open Kiwi Browser's Settings, choose Privacy and Security and then choose Use secure DNS, this is where you manage the settings for DoH. It's been a while since I touch this setting on Chromium PC but as I recall it's also on Privacy and Security.

You won't be seeing this feature as it's enabled and locked by default, unless you can provide evidence showing this feature is off, it is very hard for me to reproduce. I hope you understand.
Feel free to reply with any information that you find.

**Comment by iahung2** [comment]
> > > Could you please elaborate? I'm pretty sure Fifo already has this.
> > 
> > 
> > No. I don't think Fifo already has this feature. I'm currently not using my PC so I can't give you screenshots. You could search for `DNS over HTTPS Chromium` on Google and you could see how the feature is like. If you are on mobile like me, open Kiwi Browser's Settings, choose Privacy and Security and then choose Use secure DNS, this is where you manage the settings for DoH. It's been a while since I touch this setting on Chromium PC but as I recall it's also on Privacy and Security.
> 
> You won't be seeing this feature as it's enabled and locked by default, unless you can provide evidence showing this feature is off, it is very hard for me to reproduce. I hope you understand. Feel free to reply with any information that you find.

It's not available so how could it is off? Too lazy even to do a Google search? Why am I wasting time with your browser?

See:

![Capture](https://github.com/snaildos/Fifo-Browser/assets/137106081/ac1a278a-e5e5-436b-8c62-365d51f0a257)

(On the screenshot, you could see that I'm setting it to use Cloudflare's DoH).

Or if this is not enough, see: https://developers.cloudflare.com/1.1.1.1/encryption/dns-over-https/encrypted-dns-browsers/

Btw, you won't be see me again. Goodbye.

**Comment by snaildos** [comment]
> > > > Could you please elaborate? I'm pretty sure Fifo already has this.
> > > 
> > > 
> > > No. I don't think Fifo already has this feature. I'm currently not using my PC so I can't give you screenshots. You could search for `DNS over HTTPS Chromium` on Google and you could see how the feature is like. If you are on mobile like me, open Kiwi Browser's Settings, choose Privacy and Security and then choose Use secure DNS, this is where you manage the settings for DoH. It's been a while since I touch this setting on Chromium PC but as I recall it's also on Privacy and Security.
> > 
> > You won't be seeing this feature as it's enabled and locked by default, unless you can provide evidence showing this feature is off, it is very hard for me to reproduce. I hope you understand. Feel free to reply with any information that you find.
> 
> It's not available so how could it is off? Too lazy even to do a Google search? Why am I wasting time with your browser?
> 
> See:
> 
> ![Capture](https://github.com/snaildos/Fifo-Browser/assets/137106081/ac1a278a-e5e5-436b-8c62-365d51f0a257)
> 
> (On the screenshot, you could see that I'm setting it to use Cloudflare's DoH).
> 
> Or if this is not enough, see: https://developers.cloudflare.com/1.1.1.1/encryption/dns-over-https/encrypted-dns-browsers/
> 
> Btw, you won't be seeing me again. Goodbye.

Hello, thank you for your reply, I did research this but couldn't find any infomation of Fifo having it off. This is a quote from electron documentary. ""automatic", DoH lookups will be performed first if DoH is available, and insecure DNS lookups will be performed as a fallback."
DNS is already looked up by default over http. As of now, there is no setting to adjust the config. If that's something you are requesting, please let me know.
Thank you
