### ISSUE TITLE
mac version?

### ISSUE THREAD

**Issue by isaboo** [snaildos/Fifo-Browser#76]
**Is your feature request related to a problem? Please describe.**
No mac version

**Describe the solution you'd like**
A mac binary

**Comment by snaildos** [comment]
If you are on Mac, feel free to build Fifo yourself.
We can't support Mac since we don't have the hardware and the apple developer license.
If you want to see our projects support mac, consider donating.
https://patreon.com/snaildos

**Comment by ll3macorn** [comment]
i build it, if you want a binary message me on the snaildos discord. my username is bailey#6969

**Comment by snaildos** [comment]
> i build it, if you want a binary message me on the snaildos discord. my username is bailey#6969

Third party and unsupported, We do not provide support and will not provide assistance/not our problem if your computer gets affected, not our problem.
