### ISSUE TITLE
Make menu items in settings menu more reactive.

### ISSUE THREAD

**Issue by m-doescode** [snaildos/Fifo-Browser#80]
# Preface - this issue is completely subjective and you don't have to fix it

**Is your feature request related to a problem? Please describe.**
It is more of a small change if anything, and this opinion is kind of subjective, but I believe that the menu items in the settings menu are not reactive enough. There is only the hovered and unhovered state. Furthermore, it lacks transitions and thus is inconsistent with the design of the rest of the browser.

For example, on Microsoft Edge, when you click on a button, there are four states: not hovered, hovered, clicked, and selected.

![msedge_LUPj9UaxGI](https://user-images.githubusercontent.com/80221594/159537040-8bc8b087-3bb1-46c2-8d2d-8e4cdaaa6b75.gif)

On Fifo, similar behavior can be observed on the address bar. There are three states: not hovered, hovered, and selected and also a transition.

![Fifo_Vbf4XBr8sv](https://user-images.githubusercontent.com/80221594/159537419-818f3d0a-175b-4b8a-a5b1-adcda5f9fc28.gif)

But for whatever reason, not in the menu items in the settings screen. There is no transition, and there are only two states: not hovered, and hovered as well as a line on the side for when selected.

![Fifo_4dSTBQjV2H](https://user-images.githubusercontent.com/80221594/159537700-a833c2d8-215f-45ad-8340-46fe76bd36dd.gif)

And there's nothing wrong with this design, but it makes it inconsistent with the rest of the browser. (transition and states).

**Describe the solution you'd like**

I'd suggest that the css be tweaked a little bit adding a transition to the navigation drawer menu items as well as a selected state.

I have already made a fork with a branch and pushed the changes and I am ready to create a pull request if this feature is accepted.

Updated in fork:

![electron_FPICagZbjS](https://user-images.githubusercontent.com/80221594/159539250-35457fa4-27af-455c-ad55-425a1dfc504c.gif)

**Comment by snaildos** [comment]
Greetings,
Thank you for putting the time into this issue and your fork.
I do agree with you.
If you create a PR it will be merged.
Thank you for contributing/leaving feedback.
Kind regards,
SnailDOS
