### ISSUE TITLE
Can't configure Simple Translate extension

### ISSUE THREAD

**Issue by 3oheicrw** [snaildos/Fifo-Browser#86]
Seems extension support is not fully working. Can't set the language since it will open a new tab with error.

**Comment by snaildos** [comment]
@3oheicrw Extensions are not fully working in v1.1.0 and v1.2.0 will be released soon with FULL extension support (98% working). However, currently we are facing a problem and I can't seem to fix it on v1.2.0, if you know TypeScript, feel free to create a development environment and try to contribute (issue is #84).
Again, if you do not have experience with these languages, watch and star this repo and an update will be released in the upcoming week with extensions.👍

**Comment by snaildos** [comment]
(I'll keep this upon until v1.2.0 gets released)

**Comment by snaildos** [comment]
Also, for me to ensure the extension will work in later versions, please don't hesitate to send the extension URL, some screenshots and logs if possible to help us ensure full extension compatibility. 
Thank you so much for your issue.

**Comment by 3oheicrw** [comment]
Starred and here the extension URL:

https://chrome.google.com/webstore/detail/simple-translate/ibplnjkanclpjokhdolnendpplpjiace

**Comment by snaildos** [comment]
![image](https://user-images.githubusercontent.com/46210117/174428360-327046b4-be7f-4412-84a0-748f642d0525.png)
Supported on latest version! Please follow #89 to see when the new version will release.
Marking this issue as closed as it works on a development environment, the update is planned to be releasing this weekend. 
Thank you for your time!
