### ISSUE TITLE
7z archive warning when extracting

### ISSUE THREAD

**Issue by 3oheicrw** [snaildos/Fifo-Browser#97]
My 7zip version is the latest downloaded from their homepage. Many online sources said this warning is a bug of previous versions of 7zip and fixed in the latest version but somehow I still got it, only with your 7z releases. Both the old 1.1.0 and the latest 1.2.0 archives. The warning is: There are some data after the end of the payload data

The extracted program seems working without any problems. So it seems the archives are not corrupted. But for unknown reasons, 7zip always gives this warning.

**Comment by snaildos** [comment]
Hello,
Thank you for making multiple issues on our GitHub,
You are not meant to unextract these archives. Electron Builder generates these archives, therefor it's better to ask the issue there.

**Comment by 3oheicrw** [comment]
> Hello, Thank you for making multiple issues on our GitHub, You are not meant to unextract these archives. Electron Builder generates these archives, therefor it's better to ask the issue there.

If not meant to be extracted, what is the use of these 7z archives? I don't want to use the installer. Even though not portable these 7z archives are very handy. Just extract and use without installing.

**Comment by snaildos** [comment]
> > Hello, Thank you for making multiple issues on our GitHub, You are not meant to unextract these archives. Electron Builder generates these archives, therefor it's better to ask the issue there.
> 
> If not meant to be extracted, what is the use of these 7z archives? I don't want to use the installer. Even though not portable these 7z archives are very handy. Just extract and use without installing.

The installer is needed to use Fifo correctly (applying registry changes. usage of the auto updater) and we just don't support the use of Fifo without the installer. Compile your own portable version if that is what you want to do.
