### ISSUE TITLE
Option to not choose Fifo as default browser

### ISSUE THREAD

**Issue by 3oheicrw** [snaildos/Fifo-Browser#98]
Currently there are only two choices: Already set! and Add default browser. Choosing Already set! is the same as choose to not set Fifo as the default browser (isn't it?). I suggest changing Already set! to something else. This is somehow like you are dictating the users to set Fifo as default. I think some people will not pleased.

p/s: I personally have no problems with this, as long as I still can choose to not set Fifo as the default browser and don't have it asking this again and again. Fifo IMO is a special browser (optimized for privacy as you said) and not a general purpose browser like Edge/Chrome/Firefox so, I will not set it as the default browser. Others could have different opinions from me.

**Comment by snaildos** [comment]
+1, I do agree on this. Will be integrating on our latest versions.
(#93)
