### ISSUE TITLE
Dark Reader again

### ISSUE THREAD

**Issue by 3oheicrw** [snaildos/Fifo-Browser#99]
Installed but not working. Also unable to configure it. Clicking to the extension's icon only show "Loading. Please wait...".

**Comment by snaildos** [comment]
Issue with FEL. Will look into it soon.

**Comment by snaildos** [comment]
#104

**Comment by snaildos** [comment]
Darkreader works fine for me, the UI does not. Since this is a Manifest v3 issue, I'm not really sure what to do.
